# Generated by Django 4.2.7 on 2023-11-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('publication_date', models.DateField()),
                ('abstract', models.TextField()),
                ('body_text', models.TextField()),
                ('keywords', models.TextField()),
                ('references', models.TextField()),
                ('document_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=255)),
                ('concept_id', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
                ('synonyms', models.TextField()),
                ('hierarchical_relationships', models.TextField()),
            ],
        ),
    ]
