# Generated by Django 4.2.7 on 2023-11-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('publication_date', models.DateField()),
                ('abstract', models.TextField()),
                ('body_text', models.TextField()),
                ('keywords', models.TextField()),
                ('references', models.TextField()),
                ('document_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_version', models.CharField(max_length=50)),
                ('licensing_information', models.TextField()),
                ('dataset_source', models.CharField(max_length=255)),
                ('data_preprocessing_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelevanceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.medicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='medicalconcept',
            name='concept_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='relevancelabel',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.userquery'),
        ),
    ]
